spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_shop
    username: postgres
    password: 5Potok9-
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    change-log: classpath:db/changelog-master.xml
